version: "3.8"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: manasub
      POSTGRES_PASSWORD: manasub
      POSTGRES_DB: issm
    ports:
      - "5432:5432"
